# Minimal & stable pre-commit config

default_language_version:
  python: python3.13

repos:
  # Python formatter
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        name: Black (Python)
        types: [python]
        exclude: ^(src|frontend|node_modules|dist|build)/

  # Frontend formatter (use known-good tag)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        name: Prettier (Frontend)
        files: ^src/.*\.(js|jsx|ts|tsx|css|scss|json|md|html|yml|yaml)$
        exclude: ^(node_modules|dist|build|public)/
