# ======================================================
# 🧠 SmartDoc Enterprise - Unified Pre-Commit Configuration (v2.2 Optimized)
# ======================================================
# Ensures consistent formatting, linting, type-checking,
# and security scanning across Python (FastAPI) and
# JavaScript/React (Vite) codebases.
# Prettier is restricted to /src for faster frontend runs.
# ======================================================

default_language_version:
  python: python3.13   # ✅ Matches your SmartDoc backend environment

ci:
  skip: [trailing-whitespace, end-of-file-fixer]
  autofix_prs: true
  autoupdate_schedule: quarterly

repos:
  # ------------------------------------------------------
  # 🧹 Code Formatting - Python (Black)
  # ------------------------------------------------------
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        name: Black Code Formatter
        language_version: python3.13
        types: [python]
        exclude: ^(frontend|src|dist|node_modules|build)/

  # ------------------------------------------------------
  # 🧩 Import Sorting - Python (isort)
  # ------------------------------------------------------
  - repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
      - id: isort
        name: Isort Import Sorter
        language_version: python3.13
        types: [python]
        args: ["--profile", "black"]
        exclude: ^(frontend|src|dist|node_modules|build)/

  # ------------------------------------------------------
  # 🧪 Linting - Python (Flake8)
  # ------------------------------------------------------
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        name: Flake8 Linter
        language_version: python3.13
        additional_dependencies: ["flake8-bugbear"]
        args: ["--max-line-length=100", "--ignore=E203,W503"]
        exclude: ^(frontend|src|dist|node_modules|build)/

  # ------------------------------------------------------
  # 🔐 Security Scanning - Python (Bandit)
  # ------------------------------------------------------
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        name: Bandit Security Scanner
        args: ["-lll", "-r", "backend/app"]
        exclude: ^(tests|venv|.venv|dist|node_modules|build|frontend|src)/

  # ------------------------------------------------------
  # 🧠 Type Checking - Python (Mypy)
  # ------------------------------------------------------
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        name: Mypy Type Checker
        additional_dependencies:
          - types-requests
          - types-PyYAML
          - types-pytz
        args: ["--ignore-missing-imports", "--install-types", "--non-interactive"]
        exclude: ^(tests|venv|.venv|dist|node_modules|build|frontend|src)/

  # ------------------------------------------------------
  # 💅 Frontend Formatting - Prettier (only /src)
  # ------------------------------------------------------
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        name: Prettier Formatter (Frontend)
        files: ^src/.*\.(js|jsx|ts|tsx|json|css|scss|md|html|yaml|yml)$
        exclude: ^(node_modules|dist|build|public|backend|venv|.venv)/
        args: ["--loglevel", "warn"]

  # ------------------------------------------------------
  # 🧾 General File Hygiene
  # ------------------------------------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: mixed-line-ending
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      - id: detect-private-key
