# ======================================================
# 🧠 SmartDoc Enterprise - Unified Python Tool Config
# ======================================================

[tool.black]
line-length = 100
target-version = ["py313"]
skip-string-normalization = false
exclude = '''
/(
  \.git
  | \.venv
  | dist
  | build
  | migrations
  | tests
  | node_modules
  | frontend
  | src
)/
'''

[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
skip_gitignore = true
src_paths = ["backend/app"]

[tool.mypy]
python_version = "3.13"
ignore_missing_imports = true
disallow_untyped_defs = false
check_untyped_defs = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
follow_imports = "skip"

[tool.bandit]
skips = ["B101", "B404", "B603", "B607"]
exclude = ["tests", "node_modules", "frontend", "dist"]
